services:
  - type: web
    name: fastapi-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
    plan: free
